Configuratron:
  sfreq: 200
  preload: True
  deep1010: True
  preload: True
architecture:
  do: 0.38
  s_growth: 32
  t_filters: 64
  pooling: 50
  temp_layers: 16
  spat_layers: 8
use_gpu: True
test_fraction: 0.2
datasets:
  clencher:
    dataset_id: 1
    name: "CogSci clencher"
    toplevel: "./data_nn/"
    filename_format: "grasp_{subject}_{session}_raw"
    tmin: -0.1
    tlen: 4.0
    data_min: True
    data_max: True
    hpf: 0.1
    lpf: 49
    notch_freq: 50
    events:
      114: "r"
      110: "n"
    picks:
      - "C3"
      - "P3"
    lr: 0.000001
    train_params:
      folds: 3
      validation_fraction: 0.35
    training_configuration:
      batch_size: 4
      epochs: 200
      