Configuratron:
  sfreq: 200
  preload: True
  deep1010: True
  preload: True
  architecture:
    layers: 16
    activation: 'relu'
    dropout: 0.1
use_gpu: True
test_fraction: 0.2
datasets:
  clencher:
    dataset_id: 1
    name: "CogSci clencher"
    toplevel: "./data_nn/"
    filename_format: "grasp_{subject}_{session}_raw"
    tmin: -0.1
    tlen: 4.0
    data_min: True
    data_max: True
    hpf: 0.1
    lpf: 49
    notch_freq: 50
    events:
      114: "r"
      110: "n"
    picks:
      - "C3"
      - "P3"
    lr: 0.0001
    train_params:
      folds: 3
    training_configuration:
      batch_size: 6
      epochs: 50
      