Configuratron:
  sfreq: 150
  preload: True
  deep1010: True
architecture:
  do: 0.37
  s_growth: 32
  t_filters: 32
  pooling: 40
  temp_layers: 15
  spat_layers: 24
use_gpu: True
datasets:
  clencher:
    dataset_id: 1
    name: "CogSci clencher"
    toplevel: "./data_nn/"
    filename_format: "grasp_{subject}_{session}_raw"
    tmin: -0.2
    tlen: 4.1
    data_min: -0.0951
    data_max: 114.0
    hpf: 0.1
    lpf: 46
    use_avg_ref: True
    notch_freq: 50
    events:
      114: "r"
      110: "n"
    picks:
      - "C3"
      - "P3"
    lr: 0.00001
    train_params:
      # folds: 3
      validation_fraction: 0.35
    training_configuration:
      batch_size: 7
      epochs: 200
      balance_method: "undersample"
      