Configuratron:
  sfreq: 64
  preload: True
  deep1010: True
model_args:
  #context_do: 0.15
  do: 0.09
  t_len: 11
  D: 2
  stride_width: 1
  F1: 8
  F2: 16
  # s_growth: 24
  # t_filters: 32
  pooling: 5
  # temp_layers: 8
  # spat_layers: 8
  # temp_span: 0.05
  # bottleneck: 3
classifier_args:
  l2_weight_decay: 0.28
  label_smoothing: null
  learning_rate: 0.001
fit_args:
  batch_size: 6
  epochs: 10000
  balance_method: "undersample"
  train_log_interval: null
use_gpu: True
datasets:
  clencher:
    dataset_id: 1
    name: "CogSci clencher"
    toplevel: "./data_nn/"
    filename_format: "grasp_{subject}_{session}_raw"
    tmin: -0.05
    tlen: 0.25
    data_min: 114.0
    data_max: -0.0248
    hpf: 8
    lpf: 32
    use_avg_ref: True
    # notch_freq: 50
    events:
      114: "r"
      110: "n"
    picks:
      - "C3"
      - "P3"
    split_args:
      validation_fraction: 0.35
    
      